apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
spec:
 selector:
  matchLabels:
   app: mysql
 replicas: 1
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
    - name: mysql
      image: mysql:8.0
      env:
      - name: MYSQL_DATABASE
        value: mydb
      - name: MYSQL_ROOT_PASSWORD
        value: rootpass
      ports:
      - containerPort: 3306
